services:
  mealieshopper:
    image: ghcr.io/helmerznl/mealieshopper:latest
    container_name: mealieshopper
    restart: unless-stopped
    pull_policy: always
    env_file:
      - .env.unraid
    ports:
      - "5959:8000"
    volumes:
      - "/mnt/user/appdata/mealieshopper:/data"
